# remote cosmographer
#cosmographerEndpoint: "tcp://10.42.0.1:44447"
cosmographerEndpoint: "ipc:///tmp/cosmographer"

# fullscreen
#glimpseWidth: 192
#glimpseHeight: 108
#pixelSize: 10
#fullscreen: false

# square
glimpseWidth: 200
glimpseHeight: 200
pixelSize: 5
fullscreen: false

