# remote cosmographer
cosmographerEndpoint: "tcp://clotho-spring:44442"
#cosmographerEndpoint: "ipc:///tmp/cosmographer"

# fullscreen
glimpseWidth: 192
glimpseHeight: 108
pixelSize: 10
fullscreen: true

# square
# glimpseWidth: 200
# glimpseHeight: 200
# pixelSize: 5
# fullscreen: false

