#ifndef PALANTIR_CONSTANTS_H
#define PALANTIR_CONSTANTS_H

#define LOGGER_NAME "palantir"
#define COSMOGRAPHER_ENDPOINT "ipc:///tmp/cosmographer_palantir"
#define LUMINARY_WIDTH 100
#define LUMINARY_HEIGHT 74
#define PIXEL_SIZE 10
#define WINDOW_WIDTH LUMINARY_WIDTH * PIXEL_SIZE
#define WINDOW_HEIGHT LUMINARY_HEIGHT * PIXEL_SIZE

#endif //PALANTIR_CONSTANTS_H
