#ifndef PALANTIR_CONSTANTS_H
#define PALANTIR_CONSTANTS_H

#define COSMOGRAPHER_ENDPOINT "ipc:///tmp/cosmographer"
#define GLIMPSE_WIDTH 100
#define GLIMPSE_HEIGHT 74
#define PIXEL_SIZE 12

#endif //PALANTIR_CONSTANTS_H
